List<Map<String, String>> currencyName = [
  {"name": "Argentine Peso", "code": "ARS"},
  {"name": "Australian Dollar", "code": "AUD"},
  {"name": "Bahamian Dollar", "code": "BSD"},
  {"name": "Brazilian Real", "code": "BRL"},
  {"name": "Bulgarian Lev", "code": "BGN"},
  {"name": "Canadian Dollar", "code": "CAD"},
  {"name": "Chilean Peso", "code": "CLP"},
  {"name": "Chinese Renminbi", "code": "CNY"},
  {"name": "Colombian Peso", "code": "COP"},
  {"name": "Croatian Kuna", "code": "HRK"},
  {"name": "Czech Koruna", "code": "CZK"},
  {"name": "Danish Krone", "code": "DKK"},
  {"name": "Dominican Peso", "code": "DOP"},
  {"name": "Euro", "code": "EUR"},
  {"name": "Fiji Dollar", "code": "FJD"},
  {"name": "Guatemalan Quetzal", "code": "GTQ"},
  {"name": "Hong Kong Dollar", "code": "HKD"},
  {"name": "Hungarian Forint", "code": "HUF"},
  {"name": "Icelandic Krona", "code": "ISK"},
  {"name": "Indonesian Rupiah", "code": "IDR"},
  {"name": "Israeli Shekel", "code": "ILS"},
  {"name": "Indian Rupee", "code": "INR"},
  {"name": "Japanese Yen", "code": "JPY"},
  {"name": "Kazakhstani Tenge", "code": "KZT"},
  {"name": "Malaysian Ringgit", "code": "MYR"},
  {"name": "Mexican Peso", "code": "MXN"},
  {"name": "Norwegian Krone", "code": "NOK"},
  {"name": "New Taiwan Dollar", "code": "TWD"},
  {"name": "New Zealand Dollar", "code": "NZD"},
  {"name": "Pakistani Rupee", "code": "PKR"},
  {"name": "Panamanian Balboa", "code": "PAB"},
  {"name": "Paraguayan Guarani", "code": "PYG"},
  {"name": "Peruvian Nuevo Sol", "code": "PEN"},
  {"name": "Philippine Peso", "code": "PHP"},
  {"name": "Polish Zloty", "code": "PLN"},
  {"name": "Romanian Leu", "code": "RON"},
  {"name": "Russian Ruble", "code": "RUB"},
  {"name": "Saudi Riyal", "code": "SAR"},
  {"name": "Singapore Dollar", "code": "SGD"},
  {"name": "South African Rand", "code": "ZAR"},
  {"name": "Swedish Krona", "code": "SEK"},
  {"name": "Swiss Franc", "code": "CHF"},
  {"name": "Thai Baht", "code": "THB"},
  {"name": "Turkish Lira", "code": "TRY"},
  {"name": "Ukrainian Hryvnia", "code": "UAH"},
  {"name": "United States Dollar", "code": "USD"},
  {"name": "Uruguayan Peso", "code": "UYU"},
  {"name": "Vietnamese Dong", "code": "VND"}
];
